version: "3"

services:
  openldap:
    image: "osixia/openldap:1.4.0"
    ports:
      - "389:389"
    volumes:
      - "/var/lib/ldap:/var/lib/ldap"
      - "/etc/ldap/slapd.d:/etc/ldap/slapd.d"
    environment:
      - LDAP_ORGANISATION=Company
      - LDAP_DOMAIN=techinterview.com
      - LDAP_ADMIN_PASSWORD=123456
